version: '3.8'

networks:
  fire-network:
    driver: bridge

services:
  rabbitmq-service:
    image: rabbitmq:management
    container_name: rabbitmq
    env_file:
      - common.env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-guest}
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    networks:
      - fire-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  forest-simulator-service:
    build:
      context: fire-simulation
      dockerfile: Dockerfile
    container_name: fire-simulation
    env_file:
      - common.env
      - fire-simulation.env
    networks:
      - fire-network
    ports:
      - "${SIMULATOR_PORT:-5000}:5000"
    depends_on:
      - rabbitmq-service
    restart: unless-stopped

  fire-backend-service:
    build:
      context: fire-backend
      dockerfile: Dockerfile
    container_name: fire-backend
    env_file:
      - common.env
      - fire-backend.env
    networks:
      - fire-network
    ports:
      - "${BACKEND_PORT:-8181}:8181"
    restart: always
    depends_on:
      - mongo
      - rabbitmq-service
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo:
    image: mongo:latest
    networks:
      - fire-network
    volumes:
      - ./fire-configurations/data:/data/db
      - ./fire-configurations/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "${MONGO_PORT:-27017}:27017"
    restart: always

  fire-configuration-service:
    build:
      context: fire-configurations
      dockerfile: Dockerfile
    container_name: fire-configuration-service
    networks:
      - fire-network
    ports:
      - "${CONFIG_PORT:-31415}:31415"
    env_file:
      - fire-configuration.env
    depends_on:
      - mongo
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:31415/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"